-- Enable Row Level Security (RLS) recommended, but for this tool we can keep it open or public for simplicity initially.
-- You can run this in the SQL Editor of your Supabase Dashboard.

-- 1. Create 'devices' table
CREATE TABLE IF NOT EXISTS devices (
    mac TEXT PRIMARY KEY,
    ip TEXT,
    hostname TEXT,
    vendor TEXT,
    type TEXT,
    name TEXT, -- Custom name/alias
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    first_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    open_ports JSONB, -- Optional: store ports if scanned
    os_info TEXT
);

-- 2. Create 'scan_history' table
CREATE TABLE IF NOT EXISTS scan_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    device_count INTEGER,
    scan_mode TEXT,
    subnet TEXT,
    duration_seconds FLOAT
);
